### ISSUE TITLE
do you have lib and dll

### ISSUE THREAD

**Issue by liutt1312** [punisher1/gskrm-rs#1]

**Comment by punisher1** [comment]
only x86 dll

**Comment by liutt1312** [comment]
Can you share it with me?



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月26日 12:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [punisher1/gskrm-rs] do you have lib and dll (Issue #1) |

only x86 dll

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by punisher1** [comment]
> 

OK，email？

**Comment by feitian78** [comment]
Can you share it with me too?
feitian78@163.com
thks

**Comment by punisher1** [comment]
> 

已发

**Comment by luyuanyi** [comment]
Can you share it with me too?
luyuanyi@hotmail.com
thanks a lot

**Comment by wxdNow** [comment]
能发一份dll库给我吗?
[wxdnow@yeah.net]
超级感谢

**Comment by shitian2** [comment]
Can you share it with me?
shitian@ytsense.cn
thanks a lot

**Comment by maksimiliann** [comment]
Can you share it with me too? And manuals if you have.
maksimiliann1103@gmail.com
Thanks a lot

**Comment by AlexSilver75** [comment]
Can you share it with me?
a.serebryakov@live.com
thanks a lot

**Comment by DuXiaoChuang** [comment]
Can you share it with me too?
17356528078@163.com
thks

**Comment by DuXiaoChuang** [comment]
> Can you share it with me? [a.serebryakov@live.com](mailto:a.serebryakov@live.com) thanks a lot

Can you share it with me too?
[feitian78@163.com](mailto:feitian78@163.com)
thks

**Comment by DuXiaoChuang** [comment]
> Can you share it with me too? [feitian78@163.com](mailto:feitian78@163.com) thks

Can you share it with me too?
[feitian78@163.com](mailto:feitian78@163.com)
thks

**Comment by DuXiaoChuang** [comment]
> 能发一份dll库给我吗? [[wxdnow@yeah.net](mailto:wxdnow@yeah.net)] 超级感谢

Can you share it with me too?
[feitian78@163.com](mailto:feitian78@163.com)
thks

**Comment by duanchi** [comment]
> Can you share it with me? [shitian@ytsense.cn](mailto:shitian@ytsense.cn) thanks a lot

Can you share it with me too?
07.duanchi@gmail.com
thanks a lot.

**Comment by Hotangenl** [comment]
Can you share it with me too?
[naojiang@hotmail.com.com](naojiang@hotmail.com.com)
thanks

**Comment by DuXiaoChuang** [comment]
> Can you share it with me too? [naojiang@hotmail.com.com](naojiang@hotmail.com.com) thanks

youchang，wx：gandao31

**Comment by nvdoanktcn-dev** [comment]
Can you share it with me too?
nvdoanktcn@gmail.com
Thanks!

**Comment by DuXiaoChuang** [comment]
Sorry, the library & DLL are paid resources.
You may add my WeChat for further discussion.  
wx:17356528078



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2026年09月14日 13:35 |
| 收件人 | ***@***.***> |
| 抄送至 | Du ***@***.***>***@***.***> |
| 主题 | Re: [punisher1/gskrm-rs] do you have lib and dll (Issue #1) |
nvdoanktcn-dev left a comment (punisher1/gskrm-rs#1)

Can you share it with me too?
***@***.***
Thanks!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications, keep track of coding agent tasks and review pull requests on the go with GitHub Mobile for iOS and Android. Download it today!
